# Generated by Django 2.1.7 on 2019-02-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitName', models.CharField(max_length=250)),
                ('ipAdress', models.GenericIPAddressField()),
                ('device', models.CharField(default='unreachable', max_length=250)),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vLan', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='ips',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Unit'),
        ),
    ]
