# Generated by Django 2.1.7 on 2019-02-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='unitName',
        ),
    ]
