# Generated by Django 2.1.7 on 2019-03-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='userName',
            field=models.CharField(default='not assigned', max_length=250),
        ),
    ]
